### ISSUE TITLE
Bug in the CO contact sensor DTH - wrong event name sent

### ISSUE THREAD

**Issue by borice** [vseven/SmartThings_VSeven#2]
https://github.com/vseven/SmartThings_VSeven/blob/a62ad29613b70fc4fdc0480b37c46a52deefef9a/devicetypes/vseven/modified-zwave-door-window-sensor-for-co.src/modified-zwave-door-window-sensor-for-co.groovy#L124

The event name in the `sendEvent` call should be `carbonMonoxide` instead of `smoke`.

**Comment by vseven** [comment]
So the reason this was like that is SmartThings didn't recognize carbonMonoxide for the Smart Home Monitor and it wouldn't trip on CO which is why I used smoke to get it to trip.  With that said they are moving to Edge drivers and this old Groovy DTH isn't going to matter.

**Comment by soupman98** [comment]
Sad trombone....
