### ISSUE TITLE
Edge Driver

### ISSUE THREAD

**Issue by bianchijc** [vseven/SmartThings_VSeven#3]
I've been using your Custom DTH for years now and I afraid this will stop working with the new Edge. Any chance you have plans to migrate this DTH to Edge if that's even possible.

**Comment by vseven** [comment]
No, sorry.  No plans on migrating.  I haven't been keeping up with things enough to migrate anything.  With that said there are some virtual drivers on the SmartThings forum that people have made so you could setup virtual points that look at the standard contact.  See this post I actually made about just that:  https://community.smartthings.com/t/suggestions-on-integrating-standard-z-wave-contact-sensors-in-as-smoke-glass-breakage/243796

With the above said I decided to go another route and bought a EcoLink Firefighter audio module.  It pulled right into the system with no issues.  Bought one and have been debating buying a second for redundancy.  https://www.amazon.com/Ecolink-Wireless-Detector-existing-FF-ZWAVE5-ECO/dp/B071Z8NM8N

**Comment by bianchijc** [comment]
Thank you so much for the suggestions and getting back to me.

**Comment by soupman98** [comment]
Not sure I love the air gap of the Ecolink... but it is what it is.

**Comment by vseven** [comment]
> I've been using your Custom DTH for years now and I afraid this will stop working with the new Edge. Any chance you have plans to migrate this DTH to Edge if that's even possible.

Here is a even better solution and the one I'm using for some other contact sensors that aren't really contact sensors:  https://community.smartthings.com/t/st-edge-z-wave-masquerade/247120/
